baseURL = "https://arthursimiyu.com/"
languageCode = "en-us"
title = "Arthur Simiyu"
theme = "cactus"
[markup.goldmark]
    [markup.goldmark.renderer]
        hardWraps = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "classic" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false

  # Home page settings
  description = "Hello, I'm Arthur Simiyu.\n \n  Remote software engineer and founder based in Nairobi, Kenya. \n \n I build simple, practical and useful things [@KaziLabs](http://kazilabs.com) for the web"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "twitter"
    link = "https://twiter.com/artsim"
  [[params.social]]
    name = "bitbucket"
    link = "https://bitbucket.com/artsim"
  [[params.social]]
    name = "linkedin"
    link = "http://ke.linkedin.com/in/arthursimiyu"
  [[params.social]]
    name = "email"
    link = "hello@arthursimiyu.com"

